[package]
name = "wakode-auth"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
argon2.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
hmac.workspace = true
rand.workspace = true
sha2.workspace = true
subtle.workspace = true
thiserror.workspace = true
uuid = { workspace = true, features = ["v4"] }
